services:
  - type: web
    name: mycondor2-backend
    env: node
    buildCommand: npm install && npx prisma generate --force && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false 