name: Build Docker images on main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          docker build --no-cache -t my-backend-image ./backend

      - name: Build frontend Docker image
        run: |
          docker build --no-cache -t my-frontend-image ./front-end

      - name: Build and run containers
        run: |
          docker compose down || true
          docker compose up --build -d
          docker ps 